apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foot-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - secretName: foot-app-secret
      hosts:
        - foot.badr.cloud
  rules:
  - host: foot.badr.cloud
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
             service:
              name: foot-app-service
              port:
                number: 80