apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foot-app-ingress
  namespace: prod
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure   # Utilisation de l'entrée "websecure" pour HTTPS
    traefik.ingress.kubernetes.io/router.tls: "true"             # Active le TLS (HTTPS)
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver  # Résolveur ACME Let's Encrypt
spec:
  rules:
  - host: foot.badr.cloud      # Le domaine pour lequel vous souhaitez activer HTTPS
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foot-app-service
            port:
              number: 80    # Le port du service interne qui sera accessible via HTTPS
  tls:
  - hosts:
    - foot.badr.cloud          # Spécifier le même domaine pour TLS
    secretName: foot-app-tls    # Nom du secret où le certificat SSL sera stocké
